### ISSUE TITLE
Index File Contents Not Generating

### ISSUE THREAD

**Issue by EchoApeiron** [eXhumer/pyTinGen#20]
I was working on setting up an index file using the script. I was able to get the base python environment setup and executed the command. It seemed to have scanned the files as shown below: 

[system@vps TinGen]# python3 TinGen.py --credentials creds/credentials.json --token creds/gdrive.token --success "Test" --index-file index.html --share-files --no-compress <gdrive_id>
Generating index
Files scanned: 5.43kfile [00:29, 1.62s/file]Adding success message to index
Creating generated index to index.html
Sharing files in index
File Share Progress: 0.00file [00:00, ?file/s]
Index Generation Completefile [00:00, ?file/s]
Files scanned: 10.8kfile [00:35, 304file/s]

However upon viewing contents of the index file this is all that is displayed: 

[system@vps TinGen]# cat index.html
TINFOIL {"files": [], "success": "Test"}

Attempted on both Windows 10 and CentOS. Both operating systems showed the same results when trying to generate an index file.

**Comment by designgears** [comment]
I had to roll back to c9269ed2a3a71a98d47a7d9d7d3f7f21d9589abc to get things working, looks like the style changes causing some issues.

**Comment by EchoApeiron** [comment]
Awesome let clone the repo from that commit and see how it works out for me.

**Comment by EchoApeiron** [comment]
Seems that commit `[c9269ed]` is currently still working as intended. I guess I would concur with your previous statement based on the commits that have been published.

**Comment by DreiPixel** [comment]
it works fine on for me.
im running with this command.
python3 TinGen.py --headless <Gdrive> --upload-to-my-drive --share-uploaded-index --add-nsw-files-without-title-id --add-non-nsw-files --no-compress


make sure that you have the "--add-non-nsw-files" if you dont use nsw files

**Comment by designgears** [comment]
`--add-non-nsw-files   Adds files without valid NSW ROM extension(NSP/NSZ/XCI/XCZ) to index`

That doesn't even make sense, tried it for lulz, doesn't change anything. All of my files have a proper extension(NSP/NSZ/XCI/XCZ).

If I add `--add-nsw-files-without-title-id` to the command it works, which tells me the regex for parsing the title-id got jacked up in those last 2 commits. That doesn't do what I need it to do because there are files I don't want in those directories.

And to prove that further, if you fix the regex, everything works fine.

`title_id_pattern = r"\[[0-9A-Fa-f]{16}\]"`
Should be 
`title_id_pattern = r"\%5B[0-9A-Fa-f]{16}\%5D"`

https://github.com/eXhumer/TinGen/pull/21/files

**Comment by eXhumer** [comment]
Closed thanks to #18. Sorry for keeping the broken code in GitHub. I fixed this locally previously, but forgot to push to GitHub.
